# Config file for [Air](https://github.com/cosmtrek/air) in TOML format

root = "."
tmp_dir = "tmp"

[build]
cmd = "make build"
bin = "build/server"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["tmp"]
exclude_regex = ["_test.go"]
delay = 100 # ms
kill_delay = 500 # ms

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true