name: check
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
jobs:
  check:
    name: check
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Configure git for private modules
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: git config --global url."https://${ACCESS_TOKEN}@github.com".insteadOf "https://github.com"

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest

      - name: Unit test
        run: go test -v .
